const arr = [
  "IT Support services",
  "Hardware and infrastructure support",
  "Web design and maintenance.",
  "Re-engineering electronic appliances to work more effectively.",
  "Expert with Microsoft windows and MS Office.",
  "Knowledge of viral protection systems.",
  "Knowledge of Enterprise Resource Planning (ERP) and support.",
  "Knowledge sharing and advice.",
  "Self-management.",
  "Ability to work in different environments.",
  "Positive attitude and energy.",
  "Leadership skill.",
  "Ability to manage inventories.",
  "Delivering Client Orientation results.",
  "Openness to change.",
  "System development and implementation.",
  "Professionalism",
  "Competence",
  "Productive",
  "Information Provision",
  "Organizational",
  "Willingness To Learn",
  "Discipline, Meeting Commitments",
  "Motivated",
  "Accountability",
  "Achieving Results",
  "Adaptability",
  "Articulate",
  "Awareness",
  "Client Orientation",
  "Conscientious",
  "Cooperation",
  "Ownership",
  "Partnerships",
  "Persistence",
  "Persuades Others",
  "Provide Advice",
  "Sensitivity",
  "Shares Credit",
  "Solve Problems",
  "Sound Judgment",
  "Teamwork",
  "Willing To Learn, Writes Clearly",
  "Network Administration",
  "Humanitarian",
  "New Technologies",
  "New Technology",
  "Cost Recovery",
  "Knowledge Building",
  "Software Packages",
  "Web Management",
  "Computer Proficiency",
  "MS Office",
  "Access To Information, Annual Plan",
  "Business Continuity",
  "Business Processes",
  "Client Services",
  "Computer Science",
  "Conduct Research",
  " Content Management",
  "Corporate Knowledge",
  "Cost Plan",
  "Electronic Components",
  "Humanitarian Assistance",
  "Communication Equipment",
  "Wireless Networks",
  "Technical Specifications",
  "Staff Training",
  "Personal Responsibility",
  "Organization Of Training",
  "Operation and Maintenance",
  "Office Management",
  "Network Wiring",
  "Network Access",
  "Negotiate Contracts",
  "Monitoring Of The Network",
  "Microsoft SharePoint",
  "MS Teams",
  "MS SharePoint",
  "Operating Systems",
  "ICT Security",
];

console.log(arr.length);
